// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/server.proto

package serverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SavedAs              string   `protobuf:"bytes,2,opt,name=savedAs,proto3" json:"savedAs,omitempty"`
	OtherName            string   `protobuf:"bytes,3,opt,name=otherName,proto3" json:"otherName,omitempty"`
	HouseAddress         string   `protobuf:"bytes,4,opt,name=houseAddress,proto3" json:"houseAddress,omitempty"`
	Area                 string   `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Landmark             string   `protobuf:"bytes,6,opt,name=landmark,proto3" json:"landmark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Address) GetSavedAs() string {
	if m != nil {
		return m.SavedAs
	}
	return ""
}

func (m *Address) GetOtherName() string {
	if m != nil {
		return m.OtherName
	}
	return ""
}

func (m *Address) GetHouseAddress() string {
	if m != nil {
		return m.HouseAddress
	}
	return ""
}

func (m *Address) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *Address) GetLandmark() string {
	if m != nil {
		return m.Landmark
	}
	return ""
}

type Shop struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locality             string   `protobuf:"bytes,3,opt,name=locality,proto3" json:"locality,omitempty"`
	Types                []string `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{1}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Shop) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type MenuItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BestSeller           bool     `protobuf:"varint,5,opt,name=bestSeller,proto3" json:"bestSeller,omitempty"`
	Weight               int32    `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{2}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MenuItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MenuItem) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MenuItem) GetBestSeller() bool {
	if m != nil {
		return m.BestSeller
	}
	return false
}

func (m *MenuItem) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Order struct {
	TotalPrice           int32    `protobuf:"varint,1,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	OrderDate            string   `protobuf:"bytes,2,opt,name=orderDate,proto3" json:"orderDate,omitempty"`
	OrderTime            string   `protobuf:"bytes,3,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	ShopId               string   `protobuf:"bytes,4,opt,name=shopId,proto3" json:"shopId,omitempty"`
	DeliveryRating       int32    `protobuf:"varint,5,opt,name=deliveryRating,proto3" json:"deliveryRating,omitempty"`
	FoodRating           int32    `protobuf:"varint,6,opt,name=foodRating,proto3" json:"foodRating,omitempty"`
	OrderDetails         string   `protobuf:"bytes,7,opt,name=orderDetails,proto3" json:"orderDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{3}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetOrderDate() string {
	if m != nil {
		return m.OrderDate
	}
	return ""
}

func (m *Order) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *Order) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *Order) GetDeliveryRating() int32 {
	if m != nil {
		return m.DeliveryRating
	}
	return 0
}

func (m *Order) GetFoodRating() int32 {
	if m != nil {
		return m.FoodRating
	}
	return 0
}

func (m *Order) GetOrderDetails() string {
	if m != nil {
		return m.OrderDetails
	}
	return ""
}

type RegisterUserRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirebaseId           string   `protobuf:"bytes,3,opt,name=firebase_id,json=firebaseId,proto3" json:"firebase_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{4}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUserRequest) GetFirebaseId() string {
	if m != nil {
		return m.FirebaseId
	}
	return ""
}

type RegisterUserResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{5}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetUserDetailsRequest struct {
	FirebaseId           string   `protobuf:"bytes,1,opt,name=firebase_id,json=firebaseId,proto3" json:"firebase_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDetailsRequest) Reset()         { *m = GetUserDetailsRequest{} }
func (m *GetUserDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailsRequest) ProtoMessage()    {}
func (*GetUserDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{6}
}

func (m *GetUserDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailsRequest.Unmarshal(m, b)
}
func (m *GetUserDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailsRequest.Merge(m, src)
}
func (m *GetUserDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailsRequest.Size(m)
}
func (m *GetUserDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailsRequest proto.InternalMessageInfo

func (m *GetUserDetailsRequest) GetFirebaseId() string {
	if m != nil {
		return m.FirebaseId
	}
	return ""
}

type GetUserDetailsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDetailsResponse) Reset()         { *m = GetUserDetailsResponse{} }
func (m *GetUserDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailsResponse) ProtoMessage()    {}
func (*GetUserDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{7}
}

func (m *GetUserDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailsResponse.Unmarshal(m, b)
}
func (m *GetUserDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailsResponse.Merge(m, src)
}
func (m *GetUserDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailsResponse.Size(m)
}
func (m *GetUserDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailsResponse proto.InternalMessageInfo

func (m *GetUserDetailsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserDetailsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserDetailsResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type UpdateUserDetailsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserDetailsRequest) Reset()         { *m = UpdateUserDetailsRequest{} }
func (m *UpdateUserDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDetailsRequest) ProtoMessage()    {}
func (*UpdateUserDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{8}
}

func (m *UpdateUserDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDetailsRequest.Unmarshal(m, b)
}
func (m *UpdateUserDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDetailsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDetailsRequest.Merge(m, src)
}
func (m *UpdateUserDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDetailsRequest.Size(m)
}
func (m *UpdateUserDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDetailsRequest proto.InternalMessageInfo

func (m *UpdateUserDetailsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserDetailsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserDetailsResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserDetailsResponse) Reset()         { *m = UpdateUserDetailsResponse{} }
func (m *UpdateUserDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDetailsResponse) ProtoMessage()    {}
func (*UpdateUserDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{9}
}

func (m *UpdateUserDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDetailsResponse.Unmarshal(m, b)
}
func (m *UpdateUserDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDetailsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDetailsResponse.Merge(m, src)
}
func (m *UpdateUserDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDetailsResponse.Size(m)
}
func (m *UpdateUserDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDetailsResponse proto.InternalMessageInfo

func (m *UpdateUserDetailsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetUserAddressRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAddressRequest) Reset()         { *m = GetUserAddressRequest{} }
func (m *GetUserAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserAddressRequest) ProtoMessage()    {}
func (*GetUserAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{10}
}

func (m *GetUserAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAddressRequest.Unmarshal(m, b)
}
func (m *GetUserAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetUserAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAddressRequest.Merge(m, src)
}
func (m *GetUserAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserAddressRequest.Size(m)
}
func (m *GetUserAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAddressRequest proto.InternalMessageInfo

func (m *GetUserAddressRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserAddressResponse struct {
	Address              []*Address `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserAddressResponse) Reset()         { *m = GetUserAddressResponse{} }
func (m *GetUserAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserAddressResponse) ProtoMessage()    {}
func (*GetUserAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{11}
}

func (m *GetUserAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAddressResponse.Unmarshal(m, b)
}
func (m *GetUserAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetUserAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAddressResponse.Merge(m, src)
}
func (m *GetUserAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserAddressResponse.Size(m)
}
func (m *GetUserAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAddressResponse proto.InternalMessageInfo

func (m *GetUserAddressResponse) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddNewAddressRequest struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewAddressRequest) Reset()         { *m = AddNewAddressRequest{} }
func (m *AddNewAddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddNewAddressRequest) ProtoMessage()    {}
func (*AddNewAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{12}
}

func (m *AddNewAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewAddressRequest.Unmarshal(m, b)
}
func (m *AddNewAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewAddressRequest.Marshal(b, m, deterministic)
}
func (m *AddNewAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewAddressRequest.Merge(m, src)
}
func (m *AddNewAddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddNewAddressRequest.Size(m)
}
func (m *AddNewAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewAddressRequest proto.InternalMessageInfo

func (m *AddNewAddressRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddNewAddressResponse struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewAddressResponse) Reset()         { *m = AddNewAddressResponse{} }
func (m *AddNewAddressResponse) String() string { return proto.CompactTextString(m) }
func (*AddNewAddressResponse) ProtoMessage()    {}
func (*AddNewAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{13}
}

func (m *AddNewAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewAddressResponse.Unmarshal(m, b)
}
func (m *AddNewAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewAddressResponse.Marshal(b, m, deterministic)
}
func (m *AddNewAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewAddressResponse.Merge(m, src)
}
func (m *AddNewAddressResponse) XXX_Size() int {
	return xxx_messageInfo_AddNewAddressResponse.Size(m)
}
func (m *AddNewAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewAddressResponse proto.InternalMessageInfo

func (m *AddNewAddressResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type UpdateAddressRequest struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAddressRequest) Reset()         { *m = UpdateAddressRequest{} }
func (m *UpdateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAddressRequest) ProtoMessage()    {}
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{14}
}

func (m *UpdateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAddressRequest.Unmarshal(m, b)
}
func (m *UpdateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAddressRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAddressRequest.Merge(m, src)
}
func (m *UpdateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAddressRequest.Size(m)
}
func (m *UpdateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAddressRequest proto.InternalMessageInfo

func (m *UpdateAddressRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type UpdateAddressResponse struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAddressResponse) Reset()         { *m = UpdateAddressResponse{} }
func (m *UpdateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAddressResponse) ProtoMessage()    {}
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{15}
}

func (m *UpdateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAddressResponse.Unmarshal(m, b)
}
func (m *UpdateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAddressResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAddressResponse.Merge(m, src)
}
func (m *UpdateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAddressResponse.Size(m)
}
func (m *UpdateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAddressResponse proto.InternalMessageInfo

func (m *UpdateAddressResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type DeleteAddressRequest struct {
	AddressId            string   `protobuf:"bytes,1,opt,name=addressId,proto3" json:"addressId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAddressRequest) Reset()         { *m = DeleteAddressRequest{} }
func (m *DeleteAddressRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressRequest) ProtoMessage()    {}
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{16}
}

func (m *DeleteAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAddressRequest.Unmarshal(m, b)
}
func (m *DeleteAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAddressRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAddressRequest.Merge(m, src)
}
func (m *DeleteAddressRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAddressRequest.Size(m)
}
func (m *DeleteAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAddressRequest proto.InternalMessageInfo

func (m *DeleteAddressRequest) GetAddressId() string {
	if m != nil {
		return m.AddressId
	}
	return ""
}

type DeleteAddressResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAddressResponse) Reset()         { *m = DeleteAddressResponse{} }
func (m *DeleteAddressResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressResponse) ProtoMessage()    {}
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{17}
}

func (m *DeleteAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAddressResponse.Unmarshal(m, b)
}
func (m *DeleteAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAddressResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAddressResponse.Merge(m, src)
}
func (m *DeleteAddressResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAddressResponse.Size(m)
}
func (m *DeleteAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAddressResponse proto.InternalMessageInfo

func (m *DeleteAddressResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetShopListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopListRequest) Reset()         { *m = GetShopListRequest{} }
func (m *GetShopListRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopListRequest) ProtoMessage()    {}
func (*GetShopListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{18}
}

func (m *GetShopListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopListRequest.Unmarshal(m, b)
}
func (m *GetShopListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopListRequest.Marshal(b, m, deterministic)
}
func (m *GetShopListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopListRequest.Merge(m, src)
}
func (m *GetShopListRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopListRequest.Size(m)
}
func (m *GetShopListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopListRequest proto.InternalMessageInfo

type GetShopListResponse struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopListResponse) Reset()         { *m = GetShopListResponse{} }
func (m *GetShopListResponse) String() string { return proto.CompactTextString(m) }
func (*GetShopListResponse) ProtoMessage()    {}
func (*GetShopListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{19}
}

func (m *GetShopListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopListResponse.Unmarshal(m, b)
}
func (m *GetShopListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopListResponse.Marshal(b, m, deterministic)
}
func (m *GetShopListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopListResponse.Merge(m, src)
}
func (m *GetShopListResponse) XXX_Size() int {
	return xxx_messageInfo_GetShopListResponse.Size(m)
}
func (m *GetShopListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopListResponse proto.InternalMessageInfo

func (m *GetShopListResponse) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

type GetShopMenuRequest struct {
	ShopId               string   `protobuf:"bytes,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopMenuRequest) Reset()         { *m = GetShopMenuRequest{} }
func (m *GetShopMenuRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopMenuRequest) ProtoMessage()    {}
func (*GetShopMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{20}
}

func (m *GetShopMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopMenuRequest.Unmarshal(m, b)
}
func (m *GetShopMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopMenuRequest.Marshal(b, m, deterministic)
}
func (m *GetShopMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopMenuRequest.Merge(m, src)
}
func (m *GetShopMenuRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopMenuRequest.Size(m)
}
func (m *GetShopMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopMenuRequest proto.InternalMessageInfo

func (m *GetShopMenuRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

type GetShopMenuResponse struct {
	Menu                 []*MenuItem `protobuf:"bytes,1,rep,name=menu,proto3" json:"menu,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetShopMenuResponse) Reset()         { *m = GetShopMenuResponse{} }
func (m *GetShopMenuResponse) String() string { return proto.CompactTextString(m) }
func (*GetShopMenuResponse) ProtoMessage()    {}
func (*GetShopMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{21}
}

func (m *GetShopMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopMenuResponse.Unmarshal(m, b)
}
func (m *GetShopMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopMenuResponse.Marshal(b, m, deterministic)
}
func (m *GetShopMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopMenuResponse.Merge(m, src)
}
func (m *GetShopMenuResponse) XXX_Size() int {
	return xxx_messageInfo_GetShopMenuResponse.Size(m)
}
func (m *GetShopMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopMenuResponse proto.InternalMessageInfo

func (m *GetShopMenuResponse) GetMenu() []*MenuItem {
	if m != nil {
		return m.Menu
	}
	return nil
}

type CreateNewOrderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewOrderRequest) Reset()         { *m = CreateNewOrderRequest{} }
func (m *CreateNewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewOrderRequest) ProtoMessage()    {}
func (*CreateNewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{22}
}

func (m *CreateNewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewOrderRequest.Unmarshal(m, b)
}
func (m *CreateNewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewOrderRequest.Merge(m, src)
}
func (m *CreateNewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewOrderRequest.Size(m)
}
func (m *CreateNewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewOrderRequest proto.InternalMessageInfo

type CreateNewOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewOrderResponse) Reset()         { *m = CreateNewOrderResponse{} }
func (m *CreateNewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNewOrderResponse) ProtoMessage()    {}
func (*CreateNewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{23}
}

func (m *CreateNewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewOrderResponse.Unmarshal(m, b)
}
func (m *CreateNewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateNewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewOrderResponse.Merge(m, src)
}
func (m *CreateNewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNewOrderResponse.Size(m)
}
func (m *CreateNewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewOrderResponse proto.InternalMessageInfo

type GetPreviousOrdersRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPreviousOrdersRequest) Reset()         { *m = GetPreviousOrdersRequest{} }
func (m *GetPreviousOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetPreviousOrdersRequest) ProtoMessage()    {}
func (*GetPreviousOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{24}
}

func (m *GetPreviousOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreviousOrdersRequest.Unmarshal(m, b)
}
func (m *GetPreviousOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreviousOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetPreviousOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreviousOrdersRequest.Merge(m, src)
}
func (m *GetPreviousOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetPreviousOrdersRequest.Size(m)
}
func (m *GetPreviousOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreviousOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreviousOrdersRequest proto.InternalMessageInfo

func (m *GetPreviousOrdersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetPreviousOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPreviousOrdersResponse) Reset()         { *m = GetPreviousOrdersResponse{} }
func (m *GetPreviousOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetPreviousOrdersResponse) ProtoMessage()    {}
func (*GetPreviousOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{25}
}

func (m *GetPreviousOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreviousOrdersResponse.Unmarshal(m, b)
}
func (m *GetPreviousOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreviousOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetPreviousOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreviousOrdersResponse.Merge(m, src)
}
func (m *GetPreviousOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetPreviousOrdersResponse.Size(m)
}
func (m *GetPreviousOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreviousOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreviousOrdersResponse proto.InternalMessageInfo

func (m *GetPreviousOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "serverpb.Address")
	proto.RegisterType((*Shop)(nil), "serverpb.Shop")
	proto.RegisterType((*MenuItem)(nil), "serverpb.MenuItem")
	proto.RegisterType((*Order)(nil), "serverpb.Order")
	proto.RegisterType((*RegisterUserRequest)(nil), "serverpb.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "serverpb.RegisterUserResponse")
	proto.RegisterType((*GetUserDetailsRequest)(nil), "serverpb.GetUserDetailsRequest")
	proto.RegisterType((*GetUserDetailsResponse)(nil), "serverpb.GetUserDetailsResponse")
	proto.RegisterType((*UpdateUserDetailsRequest)(nil), "serverpb.UpdateUserDetailsRequest")
	proto.RegisterType((*UpdateUserDetailsResponse)(nil), "serverpb.UpdateUserDetailsResponse")
	proto.RegisterType((*GetUserAddressRequest)(nil), "serverpb.GetUserAddressRequest")
	proto.RegisterType((*GetUserAddressResponse)(nil), "serverpb.GetUserAddressResponse")
	proto.RegisterType((*AddNewAddressRequest)(nil), "serverpb.AddNewAddressRequest")
	proto.RegisterType((*AddNewAddressResponse)(nil), "serverpb.AddNewAddressResponse")
	proto.RegisterType((*UpdateAddressRequest)(nil), "serverpb.UpdateAddressRequest")
	proto.RegisterType((*UpdateAddressResponse)(nil), "serverpb.UpdateAddressResponse")
	proto.RegisterType((*DeleteAddressRequest)(nil), "serverpb.DeleteAddressRequest")
	proto.RegisterType((*DeleteAddressResponse)(nil), "serverpb.DeleteAddressResponse")
	proto.RegisterType((*GetShopListRequest)(nil), "serverpb.GetShopListRequest")
	proto.RegisterType((*GetShopListResponse)(nil), "serverpb.GetShopListResponse")
	proto.RegisterType((*GetShopMenuRequest)(nil), "serverpb.GetShopMenuRequest")
	proto.RegisterType((*GetShopMenuResponse)(nil), "serverpb.GetShopMenuResponse")
	proto.RegisterType((*CreateNewOrderRequest)(nil), "serverpb.CreateNewOrderRequest")
	proto.RegisterType((*CreateNewOrderResponse)(nil), "serverpb.CreateNewOrderResponse")
	proto.RegisterType((*GetPreviousOrdersRequest)(nil), "serverpb.GetPreviousOrdersRequest")
	proto.RegisterType((*GetPreviousOrdersResponse)(nil), "serverpb.GetPreviousOrdersResponse")
}

func init() { proto.RegisterFile("proto/server.proto", fileDescriptor_b6e0ddbe8bedca8f) }

var fileDescriptor_b6e0ddbe8bedca8f = []byte{
	// 908 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x8e, 0x93, 0x75, 0x36, 0x39, 0x29, 0x41, 0x9d, 0x6e, 0x82, 0xbb, 0x4a, 0x93, 0x68, 0x40,
	0x25, 0x12, 0x28, 0x95, 0x52, 0x2e, 0x90, 0x10, 0x48, 0xa1, 0x41, 0x51, 0xa4, 0x92, 0x56, 0x6e,
	0x73, 0x83, 0x10, 0x68, 0x36, 0x3e, 0xcd, 0x5a, 0x78, 0xd7, 0x66, 0x66, 0x76, 0xa3, 0x7d, 0x13,
	0x5e, 0x80, 0x77, 0xe0, 0x8d, 0x78, 0x0d, 0x34, 0x3f, 0xb6, 0xc7, 0xde, 0x31, 0x1b, 0xc1, 0xdd,
	0x9e, 0x9f, 0xf9, 0xce, 0x77, 0xe6, 0xcc, 0xf9, 0xd6, 0x40, 0x0a, 0x9e, 0xcb, 0xfc, 0x85, 0x40,
	0x3e, 0x47, 0x7e, 0xaa, 0x0d, 0xb2, 0x65, 0xac, 0x62, 0x44, 0xff, 0x0c, 0xa0, 0x7f, 0x9e, 0x24,
	0x1c, 0x85, 0x20, 0xbb, 0xb0, 0x9e, 0x26, 0x51, 0x70, 0x1c, 0x9c, 0x6c, 0xc7, 0xeb, 0x69, 0x42,
	0x22, 0xe8, 0x0b, 0x36, 0xc7, 0xe4, 0x5c, 0x44, 0xeb, 0xda, 0x59, 0x9a, 0xe4, 0x00, 0xb6, 0x73,
	0x39, 0x46, 0x7e, 0xcd, 0x26, 0x18, 0x6d, 0xe8, 0x58, 0xed, 0x20, 0x14, 0x1e, 0x8d, 0xf3, 0x99,
	0x40, 0x8b, 0x1b, 0xf5, 0x74, 0x42, 0xc3, 0x47, 0x08, 0xf4, 0x18, 0x47, 0x16, 0x85, 0x3a, 0xa6,
	0x7f, 0x93, 0x21, 0x6c, 0x65, 0x6c, 0x9a, 0x4c, 0x18, 0xff, 0x2d, 0xda, 0xd4, 0xfe, 0xca, 0xa6,
	0x3f, 0x43, 0xef, 0xdd, 0x38, 0x2f, 0x96, 0x38, 0x12, 0xe8, 0x4d, 0x15, 0x09, 0x43, 0x50, 0xff,
	0xd6, 0x38, 0xf9, 0x2d, 0xcb, 0x52, 0xb9, 0xb0, 0xe4, 0x2a, 0x9b, 0x0c, 0x20, 0x94, 0x8b, 0x02,
	0x15, 0xa9, 0x8d, 0x93, 0xed, 0xd8, 0x18, 0xf4, 0x8f, 0x00, 0xb6, 0x7e, 0xc4, 0xe9, 0xec, 0x4a,
	0xe2, 0xe4, 0x41, 0x25, 0x06, 0x10, 0x16, 0x3c, 0xbd, 0x35, 0xcd, 0x87, 0xb1, 0x31, 0x54, 0xe1,
	0x5b, 0x26, 0xf1, 0x2e, 0xe7, 0x0b, 0xdb, 0x74, 0x65, 0x93, 0x43, 0x80, 0x11, 0x0a, 0xf9, 0x0e,
	0xb3, 0x0c, 0xb9, 0x6e, 0x7b, 0x2b, 0x76, 0x3c, 0x64, 0x1f, 0x36, 0xef, 0x31, 0xbd, 0x1b, 0x4b,
	0xdd, 0x7a, 0x18, 0x5b, 0x8b, 0xfe, 0x1d, 0x40, 0xf8, 0x86, 0x27, 0xc8, 0x15, 0x82, 0xcc, 0x25,
	0xcb, 0xde, 0xea, 0xc2, 0x81, 0xce, 0x72, 0x3c, 0x7a, 0x28, 0x2a, 0xf1, 0x82, 0xc9, 0x92, 0x6c,
	0xed, 0xa8, 0xa2, 0xef, 0x53, 0x67, 0x64, 0xa5, 0x43, 0x55, 0x17, 0xe3, 0xbc, 0xb8, 0x4a, 0x2c,
	0x6f, 0x6b, 0x91, 0xe7, 0xb0, 0x9b, 0x60, 0x96, 0xce, 0x91, 0x2f, 0x62, 0x26, 0xd3, 0xe9, 0x9d,
	0x66, 0x1e, 0xc6, 0x2d, 0xaf, 0xe2, 0xf6, 0x21, 0xcf, 0x13, 0x9b, 0x63, 0x3a, 0x70, 0x3c, 0xea,
	0x49, 0x18, 0x2a, 0x28, 0x59, 0x9a, 0x89, 0xa8, 0x6f, 0x9e, 0x84, 0xeb, 0xa3, 0x23, 0x78, 0x12,
	0xe3, 0x5d, 0x2a, 0x24, 0xf2, 0x1b, 0x81, 0x3c, 0xc6, 0xdf, 0x67, 0x28, 0xa4, 0xa2, 0x36, 0xc9,
	0x47, 0x69, 0x86, 0x76, 0x24, 0xd6, 0xf2, 0x8e, 0xe5, 0x08, 0x76, 0x3e, 0xa4, 0x1c, 0x47, 0x4c,
	0xe0, 0xaf, 0x69, 0x62, 0xdb, 0x84, 0xd2, 0x75, 0x95, 0xd0, 0x53, 0x18, 0x34, 0x6b, 0x88, 0x22,
	0x9f, 0x0a, 0xd3, 0xbf, 0x64, 0x72, 0x26, 0xca, 0x22, 0xc6, 0xa2, 0x5f, 0xc3, 0xde, 0x25, 0x4a,
	0x95, 0x6a, 0x59, 0x96, 0xac, 0x5a, 0x95, 0x82, 0xa5, 0x4a, 0xef, 0x61, 0xbf, 0x7d, 0xd2, 0xd6,
	0x7a, 0xc8, 0xfb, 0xaa, 0x9b, 0xde, 0x70, 0x9b, 0xa6, 0xdf, 0x41, 0x74, 0x53, 0x24, 0x4c, 0xa2,
	0x87, 0xd2, 0x03, 0x70, 0xe9, 0x4b, 0x78, 0xea, 0x39, 0xbf, 0xe2, 0x12, 0x5e, 0x54, 0x97, 0x60,
	0xb7, 0xd7, 0x19, 0xcd, 0x4c, 0x20, 0xbf, 0x2a, 0xab, 0x5a, 0x8b, 0xfe, 0x50, 0xf5, 0x5e, 0x1d,
	0xb0, 0x25, 0xbe, 0x80, 0x3e, 0xb3, 0xaa, 0x10, 0x1c, 0x6f, 0x9c, 0xec, 0x9c, 0x3d, 0x3e, 0x2d,
	0xa5, 0xe8, 0xb4, 0xcc, 0x2d, 0x33, 0xe8, 0x2b, 0x18, 0x9c, 0x27, 0xc9, 0x35, 0xde, 0xb7, 0xca,
	0x36, 0x40, 0x82, 0x15, 0x20, 0x17, 0xb0, 0xd7, 0x02, 0xf1, 0x51, 0x09, 0x56, 0x53, 0x31, 0xf7,
	0xf6, 0x3f, 0xa9, 0xb4, 0x40, 0xfe, 0x0b, 0x95, 0xaf, 0x60, 0x70, 0x81, 0x19, 0x2e, 0x51, 0x39,
	0x80, 0x6d, 0x9b, 0x52, 0xcd, 0xa3, 0x76, 0xa8, 0x19, 0xb6, 0x4e, 0xad, 0x18, 0xfa, 0x00, 0xc8,
	0x25, 0x4a, 0xa5, 0xb9, 0xaf, 0x53, 0x21, 0x6d, 0x11, 0xfa, 0x0d, 0x3c, 0x69, 0x78, 0x2d, 0xc8,
	0x67, 0x10, 0x2a, 0xc1, 0x28, 0x87, 0xba, 0x5b, 0xd3, 0x57, 0xa9, 0xb1, 0x09, 0xd2, 0x2f, 0x2b,
	0x48, 0xa5, 0xb5, 0xce, 0x23, 0xb2, 0xd2, 0x13, 0xb8, 0xd2, 0x43, 0xbf, 0xad, 0x4a, 0x99, 0x6c,
	0x5b, 0xea, 0x39, 0xf4, 0x26, 0x38, 0x9d, 0xd9, 0x4a, 0xa4, 0xae, 0x54, 0xea, 0x77, 0xac, 0xe3,
	0xf4, 0x13, 0xd8, 0x7b, 0xc5, 0x91, 0x49, 0xbc, 0xc6, 0x7b, 0xad, 0x9f, 0x65, 0x0b, 0x11, 0xec,
	0xb7, 0x03, 0x06, 0x9a, 0x9e, 0x41, 0x74, 0x89, 0xf2, 0x2d, 0xc7, 0x79, 0x9a, 0xcf, 0x84, 0x8e,
	0xad, 0x7c, 0xea, 0x17, 0xf0, 0xd4, 0x73, 0xc6, 0x72, 0xfd, 0x1c, 0x36, 0xb5, 0xc2, 0x95, 0xf7,
	0xf2, 0x71, 0xcd, 0xd6, 0x54, 0xb6, 0xe1, 0xb3, 0xbf, 0xfa, 0x50, 0xfd, 0x25, 0x93, 0x37, 0xf0,
	0xc8, 0xd5, 0x28, 0xf2, 0xac, 0x3e, 0xe5, 0xd1, 0xc7, 0xe1, 0x61, 0x57, 0xd8, 0x76, 0xb5, 0x46,
	0x6e, 0x60, 0xb7, 0x29, 0x45, 0xe4, 0xa8, 0x3e, 0xe3, 0x95, 0xb7, 0xe1, 0x71, 0x77, 0x42, 0x05,
	0xfb, 0x0b, 0x3c, 0x5e, 0xd2, 0x12, 0x42, 0xeb, 0x83, 0x5d, 0x42, 0x35, 0xfc, 0xf4, 0x5f, 0x73,
	0x3c, 0xb4, 0xcb, 0x8f, 0x86, 0x65, 0xda, 0xcd, 0x1d, 0xf0, 0xd0, 0x6e, 0x3d, 0x77, 0xba, 0x46,
	0x62, 0xf8, 0xa8, 0x21, 0x08, 0xe4, 0xb0, 0xb1, 0x6c, 0x4b, 0x72, 0x33, 0x3c, 0xea, 0x8c, 0xbb,
	0x98, 0x8d, 0xcd, 0x76, 0x31, 0x7d, 0xba, 0xe1, 0x62, 0x7a, 0x25, 0xc1, 0x60, 0x36, 0x36, 0xd6,
	0xc5, 0xf4, 0x09, 0x80, 0x8b, 0xe9, 0x5d, 0x75, 0xba, 0x46, 0x5e, 0xc3, 0x8e, 0xb3, 0xbe, 0xe4,
	0xa0, 0x71, 0x5d, 0xad, 0x5d, 0x1f, 0x3e, 0xeb, 0x88, 0x7a, 0xd0, 0xd4, 0xee, 0x79, 0xd0, 0x9c,
	0x35, 0xf7, 0xa0, 0xb9, 0x6b, 0x6d, 0xc6, 0xdd, 0xdc, 0x4b, 0x77, 0xdc, 0xde, 0x55, 0x76, 0xc7,
	0xdd, 0xb1, 0xd2, 0xfa, 0x95, 0x2e, 0x2d, 0xa8, 0xfb, 0x4a, 0xbb, 0x36, 0xde, 0x7d, 0xa5, 0x9d,
	0x1b, 0x4e, 0xd7, 0xbe, 0x87, 0x9f, 0xaa, 0xcd, 0x1d, 0x6d, 0xea, 0xaf, 0xeb, 0x97, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xfc, 0x14, 0x19, 0x77, 0x73, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerpbClient is the client API for Serverpb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerpbClient interface {
	// User related requests
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	GetUserDetails(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error)
	UpdateUserDetails(ctx context.Context, in *UpdateUserDetailsRequest, opts ...grpc.CallOption) (*UpdateUserDetailsResponse, error)
	// Address related requests
	GetUserAddress(ctx context.Context, in *GetUserAddressRequest, opts ...grpc.CallOption) (*GetUserAddressResponse, error)
	AddNewAddress(ctx context.Context, in *AddNewAddressRequest, opts ...grpc.CallOption) (*AddNewAddressResponse, error)
	UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error)
	DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error)
	// Shop related requests
	GetShopList(ctx context.Context, in *GetShopListRequest, opts ...grpc.CallOption) (*GetShopListResponse, error)
	GetShopMenu(ctx context.Context, in *GetShopMenuRequest, opts ...grpc.CallOption) (*GetShopMenuResponse, error)
	// Order related requests
	CreateNewOrder(ctx context.Context, in *CreateNewOrderRequest, opts ...grpc.CallOption) (*CreateNewOrderResponse, error)
	GetPreviousOrders(ctx context.Context, in *GetPreviousOrdersRequest, opts ...grpc.CallOption) (*GetPreviousOrdersResponse, error)
}

type serverpbClient struct {
	cc *grpc.ClientConn
}

func NewServerpbClient(cc *grpc.ClientConn) ServerpbClient {
	return &serverpbClient{cc}
}

func (c *serverpbClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) GetUserDetails(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error) {
	out := new(GetUserDetailsResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/GetUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) UpdateUserDetails(ctx context.Context, in *UpdateUserDetailsRequest, opts ...grpc.CallOption) (*UpdateUserDetailsResponse, error) {
	out := new(UpdateUserDetailsResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/UpdateUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) GetUserAddress(ctx context.Context, in *GetUserAddressRequest, opts ...grpc.CallOption) (*GetUserAddressResponse, error) {
	out := new(GetUserAddressResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/GetUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) AddNewAddress(ctx context.Context, in *AddNewAddressRequest, opts ...grpc.CallOption) (*AddNewAddressResponse, error) {
	out := new(AddNewAddressResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/AddNewAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error) {
	out := new(UpdateAddressResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/UpdateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error) {
	out := new(DeleteAddressResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/DeleteAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) GetShopList(ctx context.Context, in *GetShopListRequest, opts ...grpc.CallOption) (*GetShopListResponse, error) {
	out := new(GetShopListResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/GetShopList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) GetShopMenu(ctx context.Context, in *GetShopMenuRequest, opts ...grpc.CallOption) (*GetShopMenuResponse, error) {
	out := new(GetShopMenuResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/GetShopMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) CreateNewOrder(ctx context.Context, in *CreateNewOrderRequest, opts ...grpc.CallOption) (*CreateNewOrderResponse, error) {
	out := new(CreateNewOrderResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/CreateNewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverpbClient) GetPreviousOrders(ctx context.Context, in *GetPreviousOrdersRequest, opts ...grpc.CallOption) (*GetPreviousOrdersResponse, error) {
	out := new(GetPreviousOrdersResponse)
	err := c.cc.Invoke(ctx, "/serverpb.serverpb/GetPreviousOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerpbServer is the server API for Serverpb service.
type ServerpbServer interface {
	// User related requests
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	GetUserDetails(context.Context, *GetUserDetailsRequest) (*GetUserDetailsResponse, error)
	UpdateUserDetails(context.Context, *UpdateUserDetailsRequest) (*UpdateUserDetailsResponse, error)
	// Address related requests
	GetUserAddress(context.Context, *GetUserAddressRequest) (*GetUserAddressResponse, error)
	AddNewAddress(context.Context, *AddNewAddressRequest) (*AddNewAddressResponse, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*UpdateAddressResponse, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error)
	// Shop related requests
	GetShopList(context.Context, *GetShopListRequest) (*GetShopListResponse, error)
	GetShopMenu(context.Context, *GetShopMenuRequest) (*GetShopMenuResponse, error)
	// Order related requests
	CreateNewOrder(context.Context, *CreateNewOrderRequest) (*CreateNewOrderResponse, error)
	GetPreviousOrders(context.Context, *GetPreviousOrdersRequest) (*GetPreviousOrdersResponse, error)
}

// UnimplementedServerpbServer can be embedded to have forward compatible implementations.
type UnimplementedServerpbServer struct {
}

func (*UnimplementedServerpbServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedServerpbServer) GetUserDetails(ctx context.Context, req *GetUserDetailsRequest) (*GetUserDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetails not implemented")
}
func (*UnimplementedServerpbServer) UpdateUserDetails(ctx context.Context, req *UpdateUserDetailsRequest) (*UpdateUserDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserDetails not implemented")
}
func (*UnimplementedServerpbServer) GetUserAddress(ctx context.Context, req *GetUserAddressRequest) (*GetUserAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddress not implemented")
}
func (*UnimplementedServerpbServer) AddNewAddress(ctx context.Context, req *AddNewAddressRequest) (*AddNewAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewAddress not implemented")
}
func (*UnimplementedServerpbServer) UpdateAddress(ctx context.Context, req *UpdateAddressRequest) (*UpdateAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (*UnimplementedServerpbServer) DeleteAddress(ctx context.Context, req *DeleteAddressRequest) (*DeleteAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (*UnimplementedServerpbServer) GetShopList(ctx context.Context, req *GetShopListRequest) (*GetShopListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopList not implemented")
}
func (*UnimplementedServerpbServer) GetShopMenu(ctx context.Context, req *GetShopMenuRequest) (*GetShopMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopMenu not implemented")
}
func (*UnimplementedServerpbServer) CreateNewOrder(ctx context.Context, req *CreateNewOrderRequest) (*CreateNewOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewOrder not implemented")
}
func (*UnimplementedServerpbServer) GetPreviousOrders(ctx context.Context, req *GetPreviousOrdersRequest) (*GetPreviousOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreviousOrders not implemented")
}

func RegisterServerpbServer(s *grpc.Server, srv ServerpbServer) {
	s.RegisterService(&_Serverpb_serviceDesc, srv)
}

func _Serverpb_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/GetUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).GetUserDetails(ctx, req.(*GetUserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_UpdateUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).UpdateUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/UpdateUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).UpdateUserDetails(ctx, req.(*UpdateUserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_GetUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).GetUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/GetUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).GetUserAddress(ctx, req.(*GetUserAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_AddNewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).AddNewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/AddNewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).AddNewAddress(ctx, req.(*AddNewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).UpdateAddress(ctx, req.(*UpdateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/DeleteAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).DeleteAddress(ctx, req.(*DeleteAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_GetShopList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).GetShopList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/GetShopList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).GetShopList(ctx, req.(*GetShopListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_GetShopMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).GetShopMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/GetShopMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).GetShopMenu(ctx, req.(*GetShopMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_CreateNewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).CreateNewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/CreateNewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).CreateNewOrder(ctx, req.(*CreateNewOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serverpb_GetPreviousOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviousOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerpbServer).GetPreviousOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.serverpb/GetPreviousOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerpbServer).GetPreviousOrders(ctx, req.(*GetPreviousOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Serverpb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.serverpb",
	HandlerType: (*ServerpbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Serverpb_RegisterUser_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _Serverpb_GetUserDetails_Handler,
		},
		{
			MethodName: "UpdateUserDetails",
			Handler:    _Serverpb_UpdateUserDetails_Handler,
		},
		{
			MethodName: "GetUserAddress",
			Handler:    _Serverpb_GetUserAddress_Handler,
		},
		{
			MethodName: "AddNewAddress",
			Handler:    _Serverpb_AddNewAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _Serverpb_UpdateAddress_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _Serverpb_DeleteAddress_Handler,
		},
		{
			MethodName: "GetShopList",
			Handler:    _Serverpb_GetShopList_Handler,
		},
		{
			MethodName: "GetShopMenu",
			Handler:    _Serverpb_GetShopMenu_Handler,
		},
		{
			MethodName: "CreateNewOrder",
			Handler:    _Serverpb_CreateNewOrder_Handler,
		},
		{
			MethodName: "GetPreviousOrders",
			Handler:    _Serverpb_GetPreviousOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server.proto",
}
